services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ['sh', '/app/docker/entrypoint.sh']
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '${NUXT_PORT:-3000}:3000'
    volumes:
      - .:/app

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:5.4.2
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '${ADMINER_PORT:-8080}:8080'

volumes:
  postgres_data:
